/*********************************************************************
*
* Example program: 
*    DAQdoubleBuf.c
*
* Description: 
*    Read a waveform from one analog input channel continuously using
*     internal timing (uses low-level NI-DAQ functions)
*
* Example Category: 
*    AI
*
* Example Task Types: 
*    BUF, 1CH, CONT, INTTIM, ASYNC, INTTRIG
*
* List of key parameters: 
*    iDBmodeON, ulCount, iSampTB, iHalfReady, lTimeout
*
*    [Since variables are hardcoded, there is no guarantee that this
*     program will work for your setup.  This example is simply
*     presented as a code snippet of how you can use NI-DAQ functions
*     to perform a task.]
*
* List of NI-DAQ Functions used in this example: 
*    Timeout_Config, NIDAQErrorHandler, DAQ_Rate, DAQ_DB_Config,
*     DAQ_Start, DAQ_DB_HalfReady, DAQ_DB_Transfer, NIDAQYield,
*     DAQ_Clear
*
*    [NOTE: For further details on each NI-DAQ function, please refer
*     to the NI-DAQ On-Line Help (NIDAQPC.HLP).]
*
* Pin Connection Information: 
*    Connect your analog signal to AI channel 1. The default analog
*     input mode for the DAQ device will be used.
*
*    [For further I/O connection details, please refer to your hardware
*     User Manual.]
*
*    [For further details on how to run this example, please refer to
*     the NI-DAQ Examples On-Line Help (NIDAQEx.HLP).]
*
*********************************************************************/
/*
 * Includes: 
 */

#include "nidaqex.h"


/*
 * Main: 
 */

void main(void)
{
    /*
     * Local Variable Declarations: 
     */

    i16 iStatus = 0;
    i16 iRetVal = 0;
    i16 iDevice = 1;
    i16 iDBmodeON = 1;
    i16 iDBmodeOFF = 0;
    i16 iChan = 1;
    i16 iGain = 1;
    u32 ulCount = 1000;
    i16 iLoopCount = 0;
    i16 iHalfBufsToRead = 20;
    f64 dSampRate = 1000.0;
    i16 iUnits = 0;
    i16 iSampTB = 0;
    u16 uSampInt = 0;
    static i16 piBuffer[1000] = {0};
    static i16 piHalfBuffer[500] = {0};
    i16 iHalfReady = 0;
    i16 iDAQstopped = 0;
    u32 ulPtsTfr = 0;
    i16 iIgnoreWarning = 0;
    i32 lTimeout = 180;
    i16 iYieldON = 1;

    /* This sets a timeout limit (#Sec * 18ticks/Sec) so that if there
     is something wrong, the program won't hang on the DAQ_DB_Transfer
     call. */

    iStatus = Timeout_Config(iDevice, lTimeout);

    iRetVal = NIDAQErrorHandler(iStatus, "Timeout_Config",
     iIgnoreWarning);

    /* Convert sample rate (S/sec) to appropriate timebase and sample
     interval values. */

    /* NOTE: If you are using a DSA device, call DAQ_Set_Clock
     instead. Refer to NI-DAQ Function Reference Manual for details. */
    

    iStatus = DAQ_Rate(dSampRate, iUnits, &iSampTB, &uSampInt);

    /* Turn ON software double-buffered mode. */

    iStatus = DAQ_DB_Config(iDevice, iDBmodeON);

    iRetVal = NIDAQErrorHandler(iStatus, "DAQ_DB_Config",
     iIgnoreWarning);

    /* Acquire data indefinitely into circular buffer from a single
     channel. If you want to acquire from multiple channels, use
     SCAN_Start of Lab_ISCAN_Start. */

    /* NOTE FOR DSA devices... DSA devices can format samples in a
     left-justified format in 32-bit data words. This means that the most
     significant bits of the data word contain the bits generated by the
     converter. When allocating data buffers, be sure to account for the
     32-bit data width. Even though a number of DAQ/SCAN/WFM functions are
     declared to accept pointers to 16-bit data buffers, you should pass
     pointers to 32-bit data buffers. Also, modify the iGain parameter to
     be in units of dB. */

    iStatus = DAQ_Start(iDevice, iChan, iGain, piBuffer, ulCount,
     iSampTB, uSampInt);

    iRetVal = NIDAQErrorHandler(iStatus, "DAQ_Start", iIgnoreWarning);
    

    /* Loop until 'iHalfBufsToRead' half buffers are acquired. HINT:
     You can be doing other foreground tasks during this time. */
    

    printf(" Continuous acquisition has started.\n");

    printf(" HINT: You can add your own graphing calls in the while loop.\n");

    while ((iLoopCount < iHalfBufsToRead) && (iStatus == 0)) {

        

        iStatus = DAQ_DB_HalfReady(iDevice, &iHalfReady,
         &iDAQstopped);

        if ((iHalfReady == 1) && (iStatus == 0)) {


            /* Grab half-buffer of data into 'piHalfBuffer'. You can
             scale the data with DAQ_VScale, or store it to disk using your own
             file I/O calls. */

            /* NOTE FOR DSA devices... DSA devices can format samples
             in a left-justified format in 32-bit data words. This means that the
             most significant bits of the data word contain the bits generated by
             the converter. When allocating data buffers, be sure to account for
             the 32-bit data width. Even though a number of DAQ/SCAN/WFM functions
             are declared to accept pointers to 16-bit data buffers, you should
             pass pointers to 32-bit data buffers. */
            
            

            iStatus = DAQ_DB_Transfer(iDevice, piHalfBuffer,
             &ulPtsTfr, &iDAQstopped);

            iRetVal = NIDAQErrorHandler(iStatus, "DAQ_DB_Transfer",
             0);

            ++iLoopCount;

            printf(" %d Half buffers acquired.\n", iLoopCount);

        }
        else {

            iRetVal = NIDAQErrorHandler(iStatus, "DAQ_DB_HalfReady",
             0);

        }


        iRetVal = NIDAQYield(iYieldON);

    }


    printf(" Continuous acquisition is done!\n");

    /* CLEANUP - Don't check for errors on purpose. */

    iStatus = DAQ_Clear(iDevice);

    /* Set DB mode back to initial state. */

    iStatus = DAQ_DB_Config(iDevice, iDBmodeOFF);

    /* Disable timeouts. */

    iStatus = Timeout_Config(iDevice, -1);


}

/* End of program */
