/*********************************************************************
*
* Example program: 
*    DAQsingleBufAnalogTrig.c
*
* Description: 
*    Read a waveform from one analog input channel upon an rising-slope
*     analog trigger using internal timing (uses low-level NI-DAQ
*     functions, ONLY for E-series devices with analog triggering
*     support)
*
* Example Category: 
*    AI
*
* Example Task Types: 
*    BUF, 1CH, BURST, INTTIM, ASYNC, ATRIG
*
* List of key parameters: 
*    lLowValue, lHighValue, iSampTB
*
*    [Since variables are hardcoded, there is no guarantee that this
*     program will work for your setup.  This example is simply
*     presented as a code snippet of how you can use NI-DAQ functions
*     to perform a task.]
*
* List of NI-DAQ Functions used in this example: 
*    Configure_HW_Analog_Trigger, NIDAQErrorHandler, Select_Signal,
*     DAQ_Rate, DAQ_Start, DAQ_Check, NIDAQYield, DAQ_VScale,
*     DAQ_Clear, NIDAQPlotWaveform
*
*    [NOTE: For further details on each NI-DAQ function, please refer
*     to the NI-DAQ On-Line Help (NIDAQPC.HLP).]
*
* Pin Connection Information: 
*    Connect your analog signal to AI channel 1. Connect the ground
*     reference of the analog signal to AIGND. The signal you connect
*     will be the analog trigger signal. The default analog input mode
*     for the DAQ device will be used. NOTE... The analog trigger
*     source can also be set to PFI0, if you set the last parameter in
*     Config_HW_Analog_Trigger to ND_PFI_0.
*
*    [For further I/O connection details, please refer to your hardware
*     User Manual.]
*
*    [For further details on how to run this example, please refer to
*     the NI-DAQ Examples On-Line Help (NIDAQEx.HLP).]
*
*********************************************************************/
/*
 * Includes: 
 */

#include "nidaqex.h"


/*
 * Main: 
 */

void main(void)
{
    /*
     * Local Variable Declarations: 
     */

    i16 iStatus = 0;
    i16 iRetVal = 0;
    i16 iDevice = 1;
    i32 lLowValue = 64;
    i32 lHighValue = 128;
    i16 iChan = 1;
    i16 iExtConv = 0;
    i16 iGain = 1;
    u32 ulCount = 100;
    f64 dGainAdjust = 1.0;
    f64 dOffset = 0.0;
    f64 dSampRate = 1000.0;
    i16 iUnits = 0;
    i16 iSampTB = 0;
    u16 uSampInt = 0;
    static i16 piBuffer[100] = {0};
    static f64 pdVoltBuffer[100] = {0.0};
    i16 iDAQstopped = 0;
    u32 ulRetrieved = 0;
    i16 iIgnoreWarning = 0;
    i16 iYieldON = 1;

    /* Setup for hardware analog trigger. */

    /* NOTE: the voltage values represented by 'lLowValue' and
     'lHighValue' will differ depending on analog input polarity and the
     number of bits of resolution of the A/D converter used in your
     E-series device.  Refer to the description for this function in the
     NI-DAQ Function Reference Manual for details. */

    iStatus = Configure_HW_Analog_Trigger(iDevice, ND_ON, lLowValue,
     lHighValue, ND_ABOVE_HIGH_LEVEL, ND_THE_AI_CHANNEL);

    iRetVal = NIDAQErrorHandler(iStatus,
     "Configure_HW_Analog_Trigger", iIgnoreWarning);

    /* Setup for external start trigger into PFI0. You can change the
     "source" to an analog input channel, if desired. */

    iStatus = Select_Signal(iDevice, ND_IN_START_TRIGGER, ND_PFI_0,
     ND_LOW_TO_HIGH);

    iRetVal = NIDAQErrorHandler(iStatus, "Select_Signal",
     iIgnoreWarning);

    /* Convert sample rate (S/sec) to appropriate timebase and sample
     interval values. */

    /* NOTE: If you are using a DSA device, call DAQ_Set_Clock
     instead. Refer to NI-DAQ Function Reference Manual for details. */
    

    iStatus = DAQ_Rate(dSampRate, iUnits, &iSampTB, &uSampInt);

    /* Acquire data from a single channel upon an analog trigger */
    

    /* NOTE FOR DSA devices... DSA devices can format samples in a
     left-justified format in 32-bit data words. This means that the most
     significant bits of the data word contain the bits generated by the
     converter. When allocating data buffers, be sure to account for the
     32-bit data width. Even though a number of DAQ/SCAN/WFM functions are
     declared to accept pointers to 16-bit data buffers, you should pass
     pointers to 32-bit data buffers. Also, modify the iGain parameter to
     be in units of dB. */

    iStatus = DAQ_Start(iDevice, iChan, iGain, piBuffer, ulCount,
     iSampTB, uSampInt);

    iRetVal = NIDAQErrorHandler(iStatus, "DAQ_Start", iIgnoreWarning);
    

    printf(" Apply your analog trigger voltage to AI channel %d\n", iChan);

    while ((iDAQstopped != 1) && (iStatus == 0)) {


        /* Loop until all acquisition is complete.  HINT: You can be
         doing other foreground tasks during this time. */

        iStatus = DAQ_Check(iDevice, &iDAQstopped, &ulRetrieved);
        

        iRetVal = NIDAQYield(iYieldON);

    }


    iRetVal = NIDAQErrorHandler(iStatus, "DAQ_Check", iIgnoreWarning);
    

    iStatus = DAQ_VScale(iDevice, iChan, iGain, dGainAdjust, dOffset,
     ulCount, piBuffer, pdVoltBuffer);

    iRetVal = NIDAQErrorHandler(iStatus, "DAQ_VScale",
     iIgnoreWarning);

    /* Don't check for errors on purose. */

    /* Set analog trigger mode back to initial state. */

    iStatus = Configure_HW_Analog_Trigger(iDevice, ND_OFF, lLowValue,
     lHighValue, ND_ABOVE_HIGH_LEVEL, ND_THE_AI_CHANNEL);

    /* Set PFI line back to initial state. */

    iStatus = Select_Signal(iDevice, ND_IN_START_TRIGGER,
     ND_AUTOMATIC, ND_DONT_CARE);

    iStatus = DAQ_Clear(iDevice);

    /* Plot acquired data */

    iRetVal = NIDAQPlotWaveform(pdVoltBuffer, ulCount, WFM_DATA_F64);
    

    printf(" The data is available in 'pdVoltBuffer'.\n");


}

/* End of program */
