/*********************************************************************
*
* Example program: 
*    DAQsingleBufExtTrig.c
*
* Description: 
*    Read a waveform from one analog input channel upon an external
*     digital trigger using internal timing (uses low-level NI-DAQ
*     functions)
*
* Example Category: 
*    AI
*
* Example Task Types: 
*    BUF, 1CH, BURST, INTTIM, ASYNC, EXTTRIG
*
* List of key parameters: 
*    iStartTrig, iSampTB
*
*    [Since variables are hardcoded, there is no guarantee that this
*     program will work for your setup.  This example is simply
*     presented as a code snippet of how you can use NI-DAQ functions
*     to perform a task.]
*
* List of NI-DAQ Functions used in this example: 
*    DAQ_Config, NIDAQErrorHandler, DAQ_Rate, DAQ_Start, DAQ_Check,
*     NIDAQYield, DAQ_VScale, DAQ_Clear, NIDAQPlotWaveform
*
*    [NOTE: For further details on each NI-DAQ function, please refer
*     to the NI-DAQ On-Line Help (NIDAQPC.HLP).]
*
* Pin Connection Information: 
*    Connect your analog signal to AI channel 1. The default analog
*     input mode for the DAQ device will be used. Also, connect a
*     digital pulse (falling edge for most DAQ devices) to the
*     'external start trigger' pin, and the ground reference to DIG
*     GND.
*
*    [For further I/O connection details, please refer to your hardware
*     User Manual.]
*
*    [For further details on how to run this example, please refer to
*     the NI-DAQ Examples On-Line Help (NIDAQEx.HLP).]
*
*********************************************************************/
/*
 * Includes: 
 */

#include "nidaqex.h"


/*
 * Main: 
 */

void main(void)
{
    /*
     * Local Variable Declarations: 
     */

    i16 iStatus = 0;
    i16 iRetVal = 0;
    i16 iDevice = 1;
    i16 iChan = 1;
    i16 iStartTrig = 1;
    i16 iExtConv = 0;
    i16 iGain = 1;
    u32 ulCount = 100;
    f64 dGainAdjust = 1.0;
    f64 dOffset = 0.0;
    f64 dSampRate = 1000.0;
    i16 iUnits = 0;
    i16 iSampTB = 0;
    u16 uSampInt = 0;
    static i16 piBuffer[100] = {0};
    static f64 pdVoltBuffer[100] = {0.0};
    i16 iDAQstopped = 0;
    u32 ulRetrieved = 0;
    i16 iIgnoreWarning = 0;
    i16 iYieldON = 1;

    /* Setup for external start trigger with iStartTrig = 1. */

    iStatus = DAQ_Config(iDevice, iStartTrig, iExtConv);

    iRetVal = NIDAQErrorHandler(iStatus, "DAQ_Config",
     iIgnoreWarning);

    /* Convert sample rate (S/sec) to appropriate timebase and sample
     interval values. */

    /* NOTE: If you are using a DSA device, call DAQ_Set_Clock
     instead. Refer to NI-DAQ Function Reference Manual for details. */
    

    iStatus = DAQ_Rate(dSampRate, iUnits, &iSampTB, &uSampInt);

    /* Acquire data from a single channel upon a digital start trigger
     */

    /* NOTE FOR DSA devices... DSA devices can format samples in a
     left-justified format in 32-bit data words. This means that the most
     significant bits of the data word contain the bits generated by the
     converter. When allocating data buffers, be sure to account for the
     32-bit data width. Even though a number of DAQ/SCAN/WFM functions are
     declared to accept pointers to 16-bit data buffers, you should pass
     pointers to 32-bit data buffers. Also, modify the iGain parameter to
     be in units of dB. */

    iStatus = DAQ_Start(iDevice, iChan, iGain, piBuffer, ulCount,
     iSampTB, uSampInt);

    iRetVal = NIDAQErrorHandler(iStatus, "DAQ_Start", iIgnoreWarning);
    

    printf(" Apply your external trigger pulse to the 'external trigger' pin.\n");

    while ((iDAQstopped != 1) && (iStatus == 0)) {


        /* Loop until all acquisition is complete.  HINT: You can be
         doing other foreground tasks during this time. */

        iStatus = DAQ_Check(iDevice, &iDAQstopped, &ulRetrieved);
        

        iRetVal = NIDAQYield(iYieldON);

    }


    iRetVal = NIDAQErrorHandler(iStatus, "DAQ_Check", iIgnoreWarning);
    

    iStatus = DAQ_VScale(iDevice, iChan, iGain, dGainAdjust, dOffset,
     ulCount, piBuffer, pdVoltBuffer);

    iRetVal = NIDAQErrorHandler(iStatus, "DAQ_VScale",
     iIgnoreWarning);

    /* CLEANUP - Don't check for errors on purpose. */

    /* Set triggering mode back to initial state. */

    iStatus = DAQ_Config(iDevice, 0, 0);

    iStatus = DAQ_Clear(iDevice);

    /* Plot acquired data */

    iRetVal = NIDAQPlotWaveform(pdVoltBuffer, ulCount, WFM_DATA_F64);
    

    printf(" The data is available in 'pdVoltBuffer'.\n");


}

/* End of program */
