/*********************************************************************
*
* Example program: 
*    SCANsingleBufSync.c
*
* Description: 
*    Read a waveform from two analog input channels using internal
*     timing (uses high-level NI-DAQ functions)
*
* Example Category: 
*    AI
*
* Example Task Types: 
*    BUF, NCH, BURST, SYNC, INTTRIG
*
* List of key parameters: 
*    lTimeout, dSampRate, dScanRate
*
*    [Since variables are hardcoded, there is no guarantee that this
*     program will work for your setup.  This example is simply
*     presented as a code snippet of how you can use NI-DAQ functions
*     to perform a task.]
*
* List of NI-DAQ Functions used in this example: 
*    Timeout_Config, NIDAQErrorHandler, SCAN_Op, SCAN_Demux,
*     DAQ_VScale, NIDAQPlotWaveform
*
*    [NOTE: For further details on each NI-DAQ function, please refer
*     to the NI-DAQ On-Line Help (NIDAQPC.HLP).]
*
* Pin Connection Information: 
*    Connect your analog signals to AI channels 1 and 2. The default
*     analog input mode for the DAQ device will be used.
*
*    [For further I/O connection details, please refer to your hardware
*     User Manual.]
*
*    [For further details on how to run this example, please refer to
*     the NI-DAQ Examples On-Line Help (NIDAQEx.HLP).]
*
*********************************************************************/
/*
 * Includes: 
 */

#include "nidaqex.h"


/*
 * Main: 
 */

void main(void)
{
    /*
     * Local Variable Declarations: 
     */

    i16 iStatus = 0;
    i16 iRetVal = 0;
    i16 iDevice = 1;
    i32 lTimeout = 180;
    i16 iNumMUXBrds = 0;
    i16 iNumChans = 2;
    i16 iChan = 1;
    i16 iGain = 1;
    f64 dSampRate = 1000.0;
    f64 dScanRate = 0.0;
    u32 ulCount = 1000;
    f64 dGainAdjust = 1.0;
    f64 dOffset = 0.0;
    static i16 piChanVect[2] = {1, 2};
    static i16 piGainVect[2] = {1, 1};
    static i16 piBuffer[1000] = {0};
    static f64 pdVoltBuffer[1000] = {0.0};
    i16 iIgnoreWarning = 0;

    /* This sets a timeout limit (#Sec * 18ticks/Sec) so that if there
     is something wrong, the program won't hang on the SCAN_Op call. */
    

    iStatus = Timeout_Config(iDevice, lTimeout);

    iRetVal = NIDAQErrorHandler(iStatus, "Timeout_Config",
     iIgnoreWarning);

    /* Acquire data from multiple channels. */

    /* HINT: If you are using a Lab or 1200 series device, replace
     this function with Lab_ISCAN_Op. */

    /* NOTE FOR DSA devices... DSA devices can format samples in a
     left-justified format in 32-bit data words. This means that the most
     significant bits of the data word contain the bits generated by the
     converter. When allocating data buffers, be sure to account for the
     32-bit data width. Even though a number of DAQ/SCAN/WFM functions are
     declared to accept pointers to 16-bit data buffers, you should pass
     pointers to 32-bit data buffers. Also, modify the elements in
     piGainVect to be in units of dB. */

    iStatus = SCAN_Op(iDevice, iNumChans, piChanVect, piGainVect,
     piBuffer, ulCount, dSampRate, dScanRate);

    iRetVal = NIDAQErrorHandler(iStatus, "SCAN_Op", iIgnoreWarning);
    

    /* NOTE FOR DSA devices... The SCAN_Demux function is not
     supported for DSA devices. If you are using a DSA device, skip the
     SCAN_Demux function and please index into the data array manually. */
    

    iStatus = SCAN_Demux(piBuffer, ulCount, iNumChans, iNumMUXBrds);
    

    iRetVal = NIDAQErrorHandler(iStatus, "SCAN_Demux",
     iIgnoreWarning);

    iStatus = DAQ_VScale(iDevice, iChan, iGain, dGainAdjust, dOffset,
     ulCount, piBuffer, pdVoltBuffer);

    iRetVal = NIDAQErrorHandler(iStatus, "DAQ_VScale",
     iIgnoreWarning);

    printf(" The plot shows Channel 1 data then Channel 2 data.\n");

    /* Plot acquired data */

    iRetVal = NIDAQPlotWaveform(pdVoltBuffer, ulCount, WFM_DATA_F64);
    

    printf(" The data is available in 'pdVoltBuffer'.\n");

    /* Disable timeouts. */

    iStatus = Timeout_Config(iDevice, -1);


}

/* End of program */
